"""Weekly digest generator — markdown summary of deal flow activity."""

from datetime import datetime, timedelta
from db.database import get_companies_with_scores, get_activity_log, get_news
from utils.formatting import fmt_money, fmt_pct, fmt_score


def generate_digest(start_date: str = None, end_date: str = None) -> str:
    """Generate a weekly digest markdown document."""
    if not start_date:
        start_date = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")
    if not end_date:
        end_date = datetime.now().strftime("%Y-%m-%d")

    companies = get_companies_with_scores()
    activities = get_activity_log(limit=200)
    news = get_news(limit=50)

    # Filter activities by date range
    period_activities = []
    for a in activities:
        ts = a.get("created_at", "")
        if ts and start_date <= ts[:10] <= end_date:
            period_activities.append(a)

    # Categorize companies
    hot_deals = [c for c in companies if c.get("tier") == "hot"]
    warm_deals = [c for c in companies if c.get("tier") == "warm"]

    # New additions in period
    new_additions = [a for a in period_activities if a.get("action") == "imported"]

    # Stage movements
    stage_changes = [a for a in period_activities if a.get("action") == "stage_changed"]

    # Summary stats
    total = len(companies)
    scored = [c for c in companies if c.get("composite_score")]
    avg_score = sum(c["composite_score"] for c in scored) / len(scored) if scored else 0
    active = sum(1 for c in companies if c.get("pipeline_stage") in ("screening", "deep_dive", "ic_review"))

    digest = f"""# Traverse Fund — Weekly Deal Flow Digest
**Mercato Partners** | **Period:** {start_date} to {end_date}
**Generated:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')}

---

## Executive Summary

- **Total Pipeline:** {total} companies tracked
- **Active Pipeline:** {active} companies in screening or later stages
- **Average Score:** {avg_score:.1f}/10
- **Hot Deals:** {len(hot_deals)} companies scoring 8.0+
- **New Additions:** {len(new_additions)} companies added this period

---

## Hot Deals ({len(hot_deals)})

Companies scoring 8.0+ on composite score — recommend IC review.

| Company | Sector | ARR | Growth | Score | Stage |
|---------|--------|-----|--------|-------|-------|
"""

    for c in sorted(hot_deals, key=lambda x: x.get("composite_score", 0), reverse=True)[:10]:
        digest += (
            f"| {c.get('name', '—')} | {c.get('sector', '—')} | "
            f"{fmt_money(c.get('arr_millions'))} | {fmt_pct(c.get('revenue_growth_pct'))} | "
            f"{fmt_score(c.get('composite_score'))} | {c.get('pipeline_stage', '—').replace('_', ' ').title()} |\n"
        )

    digest += f"""
---

## Warm Pipeline ({len(warm_deals)})

Companies scoring 6.0-7.9 — worth screening.

| Company | Sector | ARR | Growth | Score |
|---------|--------|-----|--------|-------|
"""

    for c in sorted(warm_deals, key=lambda x: x.get("composite_score", 0), reverse=True)[:10]:
        digest += (
            f"| {c.get('name', '—')} | {c.get('sector', '—')} | "
            f"{fmt_money(c.get('arr_millions'))} | {fmt_pct(c.get('revenue_growth_pct'))} | "
            f"{fmt_score(c.get('composite_score'))} |\n"
        )

    digest += "\n---\n\n## New Additions\n\n"
    if new_additions:
        for a in new_additions[:15]:
            digest += f"- **{a.get('company_name', 'Unknown')}** — {a.get('details', '')}\n"
    else:
        digest += "_No new companies added this period._\n"

    digest += "\n---\n\n## Stage Movements\n\n"
    if stage_changes:
        for a in stage_changes[:15]:
            digest += f"- **{a.get('company_name', 'Unknown')}** — {a.get('details', '')}\n"
    else:
        digest += "_No stage changes this period._\n"

    digest += f"""
---

## Thesis Match Highlights

Top companies with strongest thesis alignment:

"""
    # Show top 5 by score as thesis highlights
    top_5 = sorted(companies, key=lambda x: x.get("composite_score", 0), reverse=True)[:5]
    for i, c in enumerate(top_5, 1):
        digest += (
            f"{i}. **{c.get('name', '—')}** ({c.get('sector', '—')}) — "
            f"Score: {fmt_score(c.get('composite_score'))} | "
            f"ARR: {fmt_money(c.get('arr_millions'))} | "
            f"Growth: {fmt_pct(c.get('revenue_growth_pct'))}\n"
        )

    digest += """
---

_Generated by Traverse Radar — Mercato Partners — Building Better_
"""
    return digest
